create a blog post - Ken Kieu
kenkieu/final-project pull request #15
Opened 2021-11-02 23:13 UTC by kenkieu

Desktop:
![Kapture 2021-11-02 at 15 53 04](https://user-images.githubusercontent.com/74282257/139964195-e47b9a6a-dac4-4208-8c27-c3c7ad91a1af.gif)

Mobile
![Kapture 2021-11-02 at 16 12 40](https://user-images.githubusercontent.com/74282257/139964566-d79f81cc-483a-4130-93aa-8734933c1652.gif)

2021-11-02 23:39 UTC, thebearingedge requested changes

2021-11-02 23:39 UTC, thebearingedge commented on client/components/form.jsx
> +        };
Be sure to call it `this.setState({ ...properties... })`

2021-11-02 23:39 UTC, thebearingedge commented on server/public/index.html
> +  <link type="text/css" rel="stylesheet" href="/materialize/css/materialize.min.css" media="screen,projection" />
Instead of copying the code into your project, I recommend using a CDN.

https://cdnjs.com/libraries/materialize

2021-11-02 23:59 UTC, kenkieu commented
State being successfully reset upon submit.

![Screen Shot 2021-11-02 at 4 56 31 PM](https://user-images.githubusercontent.com/74282257/139967766-6d2d14ae-5b76-4ce1-94b7-f16acce4921f.png)

2021-11-03 00:01 UTC, thebearingedge approved these changes

2021-11-03 00:02 UTC, merged